# Generated by Django 5.0.1 on 2025-01-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CyberMazeapp", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
