# Generated by Django 5.0.1 on 2025-01-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CyberMazeapp", "0003_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("score", models.IntegerField(default=0)),
            ],
        ),
    ]
