# Generated by Django 5.0.1 on 2025-01-17 04:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CyberMazeapp", "0005_profile_delete_userscore"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="UserScore",
        ),
    ]
