# Generated by Django 5.0.1 on 2025-01-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CyberMazeapp", "0006_rename_profile_userscore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userscore",
            name="score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
